services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    ports:
      - "443:443"
    networks:
      - backend
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge